---
- block:
  - name: Install pass
    become: yes
    apt:
      name: pass
      state: latest
  when:
    - ansible_distribution == 'Debian'

- block:
  - name: Install pass
    become: yes
    pacman:
      name: pass
      state: latest
  when:
    - ansible_distribution == 'Archlinux'
