---
- name: Install base packages
  become: yes
  apt:
    name:
      - curl
      - keepassxc
      - less
      - lsb-release
      - man
      - scrot
      - silversearcher-ag
      - tree
      - wget
    state: latest
  when:
    - ansible_distribution == 'Debian'

- name: Install base packages
  become: yes
  pacman:
    name:
      - curl
      - keepassxc
      - less
      - lsb-release
      - man
      - scrot
      - the_silver_searcher
      - tree
      - wget
    state: latest
  when:
    - ansible_distribution == 'ArchLinux'
