---
- name: Install base packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - less
    - man
    - silversearcher-ag
    - tree
    - wget
    - lsb-release
    - scrot
