---
#- name: Install rxvt
#  become: yes
#  apt:
#    name: rxvt-unicode-256color
#    state: latest

- name: Install rxvt
  become: yes
  pacman:
    name:
      - rxvt-unicode
      - rxvt-unicode-truecolor
      - urxvt-perls
    state: latest

- name: Link configuration files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
  with_items:
    - .Xresources
    - .Xresources.d
