---
- block:
    - name: Install rxvt
      become: yes
      apt:
        name: rxvt-unicode-256color
        state: latest
  when:
    - ansible_distribution == 'Debian'

- block:
    - name: Install rxvt
      become: yes
      pacman:
        name:
          - rxvt-unicode
          - urxvt-perls
        state: latest
  when:
    - ansible_distribution == 'Archlinux'

- name: Link configuration files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
  with_items:
    - .Xresources
    - .Xresources.d
