---
- block:
    - name: Install LXQT
      become: yes
      pacman:
        name:
          - lxqt
          - breeze-icons
          - oxygen-icons
          - sddm
        state: latest

    - name: Enable SDDM at boot
      become: yes
      systemd:
        name: sddm
        state: started
        enabled: yes
  when:
    - ansible_distribution == 'Archlinux'
