- block:
    - name: Import aur role
      import_role:
        name: aur

    - name: Clone gcloud-sdk
      git:
        repo: https://aur.archlinux.org/google-cloud-sdk.git
        dest: ~/aur-builds/google-cloud-sdk
        # 404.0.0
        version: 3c0b1479dd2094e59132f6b3018d6cfe2c6f31a9

    - name: Build and install google-cloud-sdk
      command: makepkg --install --syncdeps --rmdeps --clean --noconfirm
      args:
        chdir: ~/aur-builds/google-cloud-sdk
  when:
    - ansible_distribution == 'Archlinux'
