#!/bin/sh

main() {
  duration_min=$1
  duration_sec=$(expr 60 \* $duration_min)
  sleep $duration_sec && xmessage "Break"
}

usage ()
{
  echo "Usage :  $0 [options] [--]

    Options:
    -d|duration   Lockout duration, in minutes (Default: 25)
    -h|help       Display this message
    -v|version    Display script version"
}

__ScriptVersion="0.1"
duration=25

while getopts ":d:hv" opt
do
  case $opt in

  d|duration) duration="$OPTARG";;
  h|help) usage; exit 0;;
  v|version)  echo "$0 -- Version $__ScriptVersion"; exit 0;;
  *) echo -e "\n Option does not exist : $OPTARG\n"
     usage; exit 1;;

  esac
done
shift $(($OPTIND-1))

main $duration
