---
- block:
  - name: Install XMonad
    become: yes
    apt:
      name: xmonad
      state: latest
  when:
    - ansible_distribution == 'Debian'

- block:
  - name: Install XMonad
    become: yes
    pacman:
      name: xmonad
      state: latest
  when:
    - ansible_distribution == 'Archlinux'

- name: Create ~/.xmonad directory
  file:
    dest: "{{ ansible_env.HOME }}/.xmonad"
    state: directory

- name: Link xmonad.hs
  file:
    src: "{{ role_path }}/files/xmonad.hs"
    dest: "{{ ansible_env.HOME }}/.xmonad/xmonad.hs"
    state: link
