---
#- name: Install packages
#  become: yes
#  apt:
#    name: "{{ item }}"
#    state: latest
#  with_items:
#    - dmenu
#    - rofi

- name: Install Rofi
  become: yes
  pacman:
    name: rofi
    state: latest

- name: Create ~/.config/rofi
  file:
    path: "{{ ansible_env.HOME }}/.config/rofi"
    state: directory
    mode: 0750

- name: Link rofi configuration
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_env.HOME }}/.config/rofi/config"
    state: link

- name: Create ~/.rasi
  file:
    path: "{{ ansible_env.HOME }}/.rasi"
    state: directory
    mode: 0750

- name: Link solarized.rasi
  file:
    src: "{{ role_path }}/files/solarized.rasi"
    dest: "{{ ansible_env.HOME }}/.rasi/solarized.rasi"
    state: link
