---
- block:
  - name: Install packages
    become: yes
    apt:
      name: rofi
      state: latest
  when:
    - ansible_distribution == 'Debian'

- block:
  - name: Install Rofi
    become: yes
    pacman:
      name: rofi
      state: latest
  when:
    - ansible_distribution == 'Archlinux'

- name: Create ~/.config/rofi
  file:
    path: "{{ ansible_env.HOME }}/.config/rofi"
    state: directory
    mode: 0750

- name: Link rofi configuration
  file:
    src: "{{ role_path }}/files/config.rasi"
    dest: "{{ ansible_env.HOME }}/.config/rofi/config.rasi"
    state: link

- name: Create ~/.rasi
  file:
    path: "{{ ansible_env.HOME }}/.rasi"
    state: directory
    mode: 0750

- name: Link solarized.rasi
  file:
    src: "{{ role_path }}/files/solarized.rasi"
    dest: "{{ ansible_env.HOME }}/.rasi/solarized.rasi"
    state: link
