---
#- name: Install Bash completion
#  become: yes
#  apt:
#    name: bash-completion
#    state: latest

- name: Install Bash completion
  become: yes
  pacman:
    name: bash-completion
    state: latest

- name: Delete ~/.profile
  file:
    path: "{{ ansible_env.HOME }}/.profile"
    state: absent

- name: Custom profile scripts
  become: yes
  copy:
    src: "{{ role_path }}/files/matt_profile.sh"
    dest: /etc/profile.d/matt_profile.sh
    mode: 0644

- name: Delete ~/.bash_profile
  file:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    state: absent

- name: Link .bash_profile
  file:
    src: "{{ role_path }}/files/.bash_profile"
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    state: link

- name: Link .bash_aliases
  file:
    src: "{{ role_path }}/files/.bash_aliases"
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    state: link

- name: Delete ~/.bashrc
  file:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: absent

- name: Link .bashrc
  file:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: link

- name: Create /etc/bashrc.d
  become: yes
  file:
    path: /etc/bashrc.d
    state: directory
    mode: 0755

- name: Support /etc/bashrc.d in /etc/bash.bashrc
  become: yes
  blockinfile:
    dest: /etc/bash.bashrc
    block: |
      if [ -d /etc/bashrc.d ]; then
        for i in /etc/bashrc.d/*.bash; do
          if [ -r $i ]; then
            . $i
          fi
        done
        unset i
      fi

- name: Copy files to /etc/bashrc.d
  become: yes
  copy:
    src: "../files/{{ item }}"
    dest: "/etc/bashrc.d/{{ item }}"
    mode: 0644
  with_items:
    - base.bash
    - matt_rc.bash

#- name: Copy Liquid Prompt
#  become: yes
#  synchronize:
#    src: ../files/liquidprompt
#    dest: /usr/local/share/
#    recursive: yes
#    delete: yes
#
#- name: Configure Liquid Prompt
#  become: yes
#  copy:
#    src: ../files/liquidpromptrc
#    dest: /etc/liquidpromptrc
#    owner: root
#    group: root
#    mode: 0644
