---
- name: Delete ~/.profile
  file:
    path: "{{ ansible_env.HOME }}/.profile"
    state: absent

- name: Custom profile scripts
  become: yes
  copy:
    src: "{{ role_path }}/files/matt.sh"
    dest: /etc/profile.d/matt.sh
    mode: 0644

- name: Link .bash_profile
  file:
    src: "{{ role_path }}/files/.bash_profile"
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    state: link

- name: Create /etc/bashrc.d
  become: yes
  file:
    path: /etc/bashrc.d
    state: directory
    mode: 0755

- name: Support /etc/bashrc.d in /etc/bash.bashrc
  become: yes
  blockinfile:
    dest: /etc/bash.bashrc
    block: |
      if [ -d /etc/bashrc.d ]; then
        for i in /etc/bashrc.d/*.bash; do
          if [ -r $i ]; then
            . $i
          fi
        done
        unset i
      fi

- name: Copy bash.bash to /etc/bashrc.d
  become: yes
  copy:
    src: ../files/base.bash
    dest: /etc/bashrc.d/base.bash
    mode: 0644
