---
- block:
  - name: Install OpenSSH client
    become: yes
    apt:
      name: openssh-client
      state: latest
  when:
    - ansible_distribution == 'Debian'

- name: Create ~/.config/systemd/user
  file:
    path: $HOME/.config/systemd/user
    state: directory

- name: Create ssh-agent.service
  copy:
    src: ../files/ssh-agent.service
    dest: $HOME/.config/systemd/user/ssh-agent.service

- name: Enable ssh-agent.service
  systemd:
    name: ssh-agent
    enabled: true
    state: started
    scope: user

- name: Create ~/.ssh
  file:
    path: $HOME/.ssh
    state: directory
    mode: 0700

- name: Create ~/.ssh/config
  file:
    path: $HOME/.ssh/config
    state: touch
    mode: 0600

- name: Add AddKeysToAgent to SSH config
  lineinfile:
    path: $HOME/.ssh/config
    regexp: "AddKeysToAgent"
    line: "  AddKeysToAgent yes"

- name: Add KillUserProcesses to logind.conf
  become: yes
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^KillUserProcesses"
    line: "KillUserProcesses=yes"

- name: Enable the systemd unit
  systemd:
    name: ssh-agent
    scope: user
    enabled: yes
    state: started
