---
- name: Link files to ~/bin
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/bin/{{ item }}"
    state: link
  loop:
    - mount-usbcrypt
    - umount-usbcrypt
    - git-init-repo.sh

- name: Add fstab for usbcrypt
  become: yes
  mount:
    src: UUID=c62fb15d-f308-4e3e-b700-16665aa4b1d0
    path: /mnt/usbcrypt
    boot: no
    fstype: ext4
    opts: noauto,rw,user
    state: present
