- block:
  - name: Install remmina
    become: yes
    apt:
      name: remmina
  when:
    - ansible_distribution == 'Debian'

- block:
  - name: Install remmina
    become: yes
    pacman:
      name: remmina
  when:
    - ansible_distribution == 'ArchLinux'
