- block:
  - name: Fetch golang
    get_url:
      url: https://golang.org/dl/go1.15.linux-amd64.tar.gz
      checksum: sha256:2d75848ac606061efe52a8068d0e647b35ce487a15bb52272c427df485193602
      dest: /tmp/go.tar.gz

  - name: Extract golang
    become: yes
    command: tar -C /usr/local -xzf /tmp/go.tar.gz

  - name: Configure Go environment variables
    become: yes
    copy:
      src: "{{ role_path }}/files/profile.d/golang.sh"
      dest: /etc/profile.d/golang.sh
      owner: root
      group: root
      mode: "0644"
  when:
    - ansible_distribution == 'Debian'

- block:
  - name: Install go
    become: yes
    pacman:
      name: go
  when:
    - ansible_distribution == 'Archlinux'
