---
- name: Install Newsboat
  become: yes
  apt:
    name: newsboat
    state: latest

- name: Create local Newsboat configuration directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ ansible_env.HOME }}/.config/newsboat"
    - "{{ ansible_env.HOME }}/.local/share/newsboat"

- name: Link Newsboat config
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_env.HOME }}/.config/newsboat/config"
    state: link

- name: Link Newsboat URLs
  file:
    src: "{{ role_path }}/files/urls"
    dest: "{{ ansible_env.HOME }}/.config/newsboat/urls"
    state: link
