---
- block:
  - name: Install xinit
    become: yes
    apt:
      name: xinit
      state: latest
  when:
    - ansible_distribution == 'Debian'

- block:
  - name: Install Xorg
    become: yes
    pacman:
      name:
        - xorg-server
        - xorg-xinit
        - xorg-xrandr
      state: present
  when:
    - ansible_distribution == 'ArchLinux'

- name: Delete ~/.xinitrc
  file:
    path: "{{ ansible_env.HOME }}/.xinitrc"
    state: absent

- name: Link .xinitrc
  file:
    src: "{{ role_path }}/files/.xinitrc"
    dest: "{{ ansible_env.HOME }}/.xinitrc"
    state: link

- name: Harden X11
  become: yes
  copy:
    src: ../files/50-matt-harden.conf
    dest: /usr/share/X11/xorg.conf.d/50-matt-harden.conf
    owner: root
    group: root
    mode: "0644"
