---
#- name: Install xinit
#  become: yes
#  apt:
#    name: xinit
#    state: latest

- name: Install Xorg
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
    state: present

- name: Delete ~/.xinitrc
  file:
    path: "{{ ansible_env.HOME }}/.xinitrc"
    state: absent

- name: Link .xinitrc
  file:
    src: "{{ role_path }}/files/.xinitrc"
    dest: "{{ ansible_env.HOME }}/.xinitrc"
    state: link
