---
- block:
  - name: Install Python3 and pip3
    become: yes
    apt:
      name:
        - python3
        - python3-pip
        - python3-distutils
      state: latest
  when:
    - ansible_distribution == 'Debian'
