---
#- name: Install Vim
#  become: yes
#  apt:
#    name: vim-nox
#    state: latest

- name: Remove Vim
  become: yes
  pacman:
    name: vim
    state: absent

- name: Install NeoVim and supporting packages
  become: yes
  pacman:
    name:
      - ansible-lint
      - autopep8
      - neovim
      - nodejs
      - npm
      - yarn
      - powerline-fonts
      - python-pylint
      - python-jedi
    state: latest

- name: Configure environment variables
  become: yes
  copy:
    src: "{{ role_path }}/files/vim_profile.sh"
    dest: /etc/profile.d/vim_profile.sh
    owner: root
    group: root
    mode: 0644

- name: Create directories
  become: yes
  file:
    dest: "/usr/local/etc/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - ""
    - "vim-config"
    - "vim-config/common"
    - "vim-config/nvim"
    - "vim-config/vim"

- name: Copy configuration
  become: yes
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/usr/local/etc/vim-config/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - common/init.vim
    - common/before_plugins.vim
    - common/plugins.vim
    - common/after_plugins.vim
    - nvim/plugins.vim
    - nvim/after_plugins.vim
    - vim/before_plugins.vim

- name: Install Vim init
  become: yes
  copy:
    src: "{{ role_path }}/files/vimrc.local"
    dest: /etc/vimrc.local
    owner: root
    group: root
    mode: 0644

- name: Load Vim init
  become: yes
  blockinfile:
    dest: /etc/vimrc
    block: |
      if filereadable("/usr/local/etc/vim-config/common/vimrc.local")
        source /usr/local/etc/vim-config/common/vimrc.local
      endif

- name: Install NeoVim init
  become: yes
  copy:
    src: "{{ role_path }}/files/vimrc.local"
    dest: /etc/xdg/nvim/sysinit.vim
    owner: root
    group: root
    mode: 0644

- name: Initialize NeoVim plugins (self)
  command: nvim -c PlugInstall -c q

- name: Initialize NeoVim plugins (root)
  become: yes
  command: nvim -c PlugInstall -c q

- name: Set directory permissions
  become: yes
  command: find /usr/local/etc/vim-config -type d -execdir chmod 0755 '{}' \;

- name: Symlink Vim to NeoVim
  become: yes
  file:
    src: /usr/bin/nvim
    dest: /usr/bin/vim
    state: link

- name: Symlink Vi to NeoVim
  become: yes
  file:
    src: /usr/bin/nvim
    dest: /usr/bin/vi
    state: link

- name: Copy CoC configuration
  copy:
    src: "{{ role_path }}/files/nvim/coc-settings.json"
    dest: "{{ ansible_env.HOME }}/.config/nvim/coc-settings.json"

