---
- name: Install apt-transport-https
  become: yes
  apt:
    name: apt-transport-https
    state: latest

- name: Add apt-key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Install Docker
  become: yes
  apt:
    name: docker-ce
    update_cache: yes
    state: latest

- name: Add to docker group
  become: yes
  command: "usermod -a -G docker {{ ansible_env.USER }}"

- name: Set Docker BUILD file repository path
  set_fact:
    docker_build_path: "{{ ansible_env.HOME }}/docker"

- name: Create Docker BUILD repository
  file:
    path: "{{ docker_build_path }}"
    state: directory
