---
- name: "Matt: Dev workstation"
  hosts: 127.0.0.1
  connection: local
  roles:
    - bash
    - git
    - base
    - wifi
    - readline
    - x11
    - menu
    - rxvt
    - slock
    - xmonad
    - sound
    - trackpad
    - debian_sources
    - netdata
    - encrypted_partition
    - python
    - web_browser
    - vim
    - alternatives
    - docker
    - dazel
    - git_lfs
    - battery
    - pass
    - autojump
    - diff
    - rss
    - mplayer
