---
- name: Base
  hosts: 127.0.0.1
  connection: local
  roles:
    - autojump
    - base
    - bash
    - diff
    - fonts
    - git
    - lockout
    - menu
    - mplayer
    - netdata
    - pass
    - python
    - readline
    - rxvt
    - slock
    - sound
    - ssh
    - usbcrypt
    - vim
    - web_browser
    - x11
    - xmonad

- name: Dev Tools
  hosts: 127.0.0.1
  connection: local
  roles:
    - wireshark
    - tasklog
    - rss
    - remmina
    - docker
    - go
    - hugo
    - k3s
  when:
    - dev_tools_enabled|default(false)

- name: Debian
  hosts: 127.0.0.1
  connection: local
  roles:
    - alternatives
    - battery
    - debian_sources
    - encrypted_partition
    - graphviz
    - pandoc
    - pomtimer
    - printer
    - suspend_hibernate
    - trackpad
    - wifi
  when:
    - ansible_distribution == 'Debian'

- name: Archlinux
  hosts: 127.0.0.1
  connection: local
  roles:
    - virt
  when:
    - ansible_distribution == 'Archlinux'

- name: Archlinux Dev Tools
  hosts: 127.0.0.1
  connection: local
  roles:
    - aws
  when:
    - ansible_distribution == 'Archlinux'
    - dev_tools_enabled|default(false)
