- block:
    - name: Import aur role
      import_role:
        name: aur

    - name: Clone anki
      git:
        repo: https://aur.archlinux.org/anki.git
        dest: ~/aur-builds/anki
        # 22.5.3-9
        version: 741141c1124289edf23aafb118ece4fbfdb63ce5

    - name: Build and install anki
      command: makepkg --install --syncdeps --rmdeps --clean --noconfirm
      args:
        chdir: ~/aur-builds/anki
  when:
    - ansible_distribution == 'Archlinux'
