- name: Install AUR helper packages
  become: yes
  pacman:
    name:
      - base-devel
      - git
    state: latest

- name: Create AUR build directory
  file:
    name: ~/aur-builds
    state: directory
