---
- block:
  - name: Install powerline fonts
    become: yes
    apt:
      name: fonts-powerline
      state: latest

  - name: Clone iosevka
    git:
      repo: https://github.com/be5invis/Iosevka
      dest: ~/src/iosevka
      # v3.4.6
      version: b873019f495a3ac63d032bac8c738cac80f21600
    # install -d ${pkgdir}/usr/share/fonts/TTF/
    # install -m644 ttf/*.ttf ${pkgdir}/usr/share/fonts/TTF/
    # install -D -m644 ${pkgname}-${pkgver}-${pkgrel}-LICENSE.md ${pkgdir}/usr/share/licenses/${pkgname}/LICENSE.md
    # sudo fc-cache
  when:
    - ansible_distribution == 'Debian'

- block:
  - name: Install powerline fonts
    become: yes
    pacman:
      name: powerline-fonts
      state: latest

  - name: Install AUR fonts
    block:
      - name: Import aur role
        import_role:
          name: aur

      - name: Clone ttf-iosevka
        git:
          repo: https://aur.archlinux.org/ttf-iosevka.git
          dest: ~/aur-builds/ttf-iosevka
          # v3.4.6
          version: d3eab4ccaae539f6339b9a8671a6eb7836626659

      - name: Build and install ttf-iosevka
        command: makepkg --install --syncdeps --rmdeps --clean --noconfirm
        args:
          chdir: ~/aur-builds/ttf-iosevka
  when:
    - ansible_distribution == 'ArchLinux'
